### PR TITLE
Add dependabot for updating submodules

### PR DESCRIPTION
**Pull request by yavko**
we should probably change interval as it'll make a pr for every update, so maybe like every 3 days

### CODE REVIEW

**Comment by flickowoa** [comment]
how about every 1 day

**Comment by flickowoa** [comment]
3days a bit too long imo

**Comment by flickowoa** [comment]
looks like its already on 1 day interval, so LGTM

**Comment by yavko** [comment]
> how about every 1 day

thats already what it is lol

**Pull request merged**
