### PR TITLE
Add new browser

### PR DESCRIPTION
**Pull request by yavko**

### CODE REVIEW

**Comment by flickowoa** [comment]
Lgtm, also when do we wanna release this

**Comment by flickowoa** [comment]
Rn only yorha uses the cleanup scripts properly

**Comment by yavko** [comment]
> Rn only yorha uses the cleanup scripts properly

we need to create theme guidelines first

**Comment by yavko** [comment]
> Lgtm, also when do we wanna release this

lets get some popular themes on here, like maybe end4's rice. we can use that to get users

**Pull request merged**
